# Generated by Django 6.0b1 on 2025-11-05 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0002_alter_propostadeemenda_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="parlamentardociclo",
            unique_together={("ciclo", "usuario")},
        ),
    ]
