# Generated by Django 6.0b1 on 2025-11-05 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, unique=True)),
                ("data_comeco", models.DateField(verbose_name="Data do Começo")),
                ("data_fim", models.DateField(verbose_name="Data do Fim")),
                ("ativo", models.BooleanField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropostaDeEmenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Título"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposta de Emenda do Ciclo",
                "verbose_name_plural": "Propostas de Emendas do Ciclo",
            },
        ),
        migrations.CreateModel(
            name="ParlamentarDoCiclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verba_inicial", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emendas.ciclo"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parlamentares do Ciclo",
            },
        ),
        migrations.CreateModel(
            name="PropostaDeEmendaDoCiclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emendas.ciclo"
                    ),
                ),
                (
                    "proposta_de_emenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emendas.propostadeemenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposta de Emenda do Ciclo",
                "verbose_name_plural": "Propostas de Emendas do Ciclo",
                "unique_together": {("proposta_de_emenda", "ciclo")},
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z_-]*$",
                                "Apenas caracteres alfanuméricos, _ e - são permitidos nesse campo.",
                            )
                        ],
                    ),
                ),
                (
                    "pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtags",
                        to="emendas.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="propostadeemenda",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="emendas", to="emendas.tag"
            ),
        ),
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_investido",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("tipo", models.CharField(max_length=20)),
                ("obs", models.TextField(blank=True, verbose_name="Observação")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="emendas.ciclo"
                    ),
                ),
                (
                    "emenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emendas.propostadeemendadociclo",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emendas.parlamentardociclo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
            },
        ),
    ]
