# Generated by Django 6.0b1 on 2025-11-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propostadeemenda",
            options={
                "verbose_name": "Proposta de Emenda",
                "verbose_name_plural": "Propostas de Emendas",
            },
        ),
    ]
