# Generated by Django 6.0b1 on 2025-11-06 15:45

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0003_alter_parlamentardociclo_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parlamentardociclo",
            options={
                "verbose_name": "Parlamentar do Ciclo",
                "verbose_name_plural": "Parlamentares do Ciclo",
            },
        ),
        migrations.AddField(
            model_name="propostadeemenda",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="parlamentardociclo",
            name="verba_inicial",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="propostadeemenda",
            name="valor",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="tag",
            name="nome",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z_-]*$",
                        "Apenas caracteres alfanuméricos, _ e - são permitidos nesse campo.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="valor_investido",
            field=models.IntegerField(),
        ),
    ]
