# Generated by Django 6.0b1 on 2025-11-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0004_alter_parlamentardociclo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="ciclo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transacoes",
                to="emendas.ciclo",
            ),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="emenda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transacoes",
                to="emendas.propostadeemendadociclo",
            ),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="parlamentar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transacoes",
                to="emendas.parlamentardociclo",
            ),
        ),
    ]
