# Generated by Django 5.2.8 on 2025-11-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0005_alter_transacao_ciclo_alter_transacao_emenda_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacao",
            name="transacao_cancelada",
            field=models.ForeignKey(
                blank=True,
                help_text="Se esta for uma transação de cancelamento, aponta para a transação original.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelamentos",
                to="emendas.transacao",
            ),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("INVESTIMENTO", "Investimento"),
                    ("CANCELAMENTO", "Cancelamento"),
                ],
                default="INVESTIMENTO",
                max_length=20,
            ),
        ),
    ]
