# Generated by Django 6.0 on 2025-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0006_transacao_transacao_cancelada_alter_transacao_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="parlamentardociclo",
            name="esfera",
            field=models.CharField(
                choices=[
                    ("FEDERAL", "Federal"),
                    ("ESTADUAL", "Estadual"),
                    ("MUNICIPAL", "Municipal"),
                ],
                default="MUNICIPAL",
                max_length=20,
            ),
        ),
    ]
