# Generated by Django 6.0 on 2025-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0007_parlamentardociclo_esfera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parlamentardociclo",
            name="esfera",
            field=models.CharField(
                choices=[
                    ("FEDERAL", "Federal"),
                    ("ESTADUAL", "Estadual"),
                    ("MUNICIPAL", "Municipal"),
                ],
                max_length=20,
            ),
        ),
    ]
