# Generated by Django 6.0 on 2025-12-17 16:26

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0008_alter_parlamentardociclo_esfera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
