# Generated by Django 6.0 on 2025-12-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0009_alter_transacao_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="emenda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transacoes",
                to="emendas.propostadeemenda",
            ),
        ),
        migrations.AddField(
            model_name="propostadeemenda",
            name="ciclo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="emendas.ciclo",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PropostaDeEmendaDoCiclo",
        ),
    ]
