# Generated by Django 6.0 on 2025-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emendas", "0010_alter_transacao_emenda_propostadeemenda_ciclo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propostadeemenda",
            name="permite_parcial",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, investimentos menores que o valor total são executáveis.",
                verbose_name="Permite Investimentos Parciais",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propostadeemenda",
            unique_together={("ciclo", "titulo")},
        ),
    ]
