# Generated by Django 6.0.3 on 2026-03-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emendas', '0011_propostadeemenda_permite_parcial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
